dist: xenial
language: generic
services:
  - docker
branches:
  only:
    - master
addons:
  apt:
    packages:
      - python3
      - python3-pip
jobs:
  include:
    - stage: lint
      name: "Linter"
      script:
        - pip3 install pyflakes pycodestyle
        - pyflakes WeeklyMenu-py/foodmenu/*.py
        - pycodestyle -r --ignore E501 WeeklyMenu-py/foodmenu/*.py
    - stage: testing
      name: "Run unit tests"
      script:
        - pip3 install Django==2.2.13
        - pip3 install django-widget-tweaks==1.4.8
        - pip3 install pytest pytest-cov pytest-django
        - COMMIT_SHA=`git rev-parse HEAD`
        - pytest --cov=./WeeklyMenu-py/foodmenu
