dist: xenial
language: generic
services:
  - docker
branches:
  only:
    - master
addons:
  apt:
    packages:
      - python3
      - python3-pip
jobs:
  include:
    - stage: lint
      name: "Linter"
      script:
        - pip3 install pyflakes pycodestyle
        - pyflakes WeeklyMenu/foodmenu/*.py
        - pycodestyle -r --ignore E501,E402,E722,W504 WeeklyMenu/foodmenu/*.py
    - stage: testing
      name: "Run unit tests"
      script:
        - pip3 install pytest pytest-cov
        - COMMIT_SHA=`git rev-parse HEAD`
        - pytest --cov=./WeeklyMenu/foodmenu"
